### ISSUE TITLE
[Question] Can this plugin make you impersonate other players?

### ISSUE THREAD

**Issue by iMrDJAi** [BeefDev/UUIDSwitcher#1]
Let's say we switch the UUID of a player into another player's UUID. Will this make that player have the other's data and inventory? and will other plugins recognize him as the other (e.g. having his permissions)?

Also, if I understand correctly, the UUID switcher only work when a player joins the server. But is it possible theoretically to switch UUID in-game without having to rejoin it again (maybe by faking player leave & join events then forcing him to re-render)?

**Comment by rievgr** [comment]
> Let's say we switch the UUID of a player into another player's UUID. Will this make that player have the other's data and inventory? and will other plugins recognize him as the other (e.g. having his permissions)?
> 
> Also, if I understand correctly, the UUID switcher only work when a player joins the server. But is it possible theoretically to switch UUID in-game without having to rejoin it again (maybe by faking player leave & join events then forcing him to re-render)?

For your first question, yes, you can use an existing player uuid and the server won't be able to tell the difference. (It works by replacing a class used by the server to retrieve the UUID from mojang servers, so the server and every plugin believes this is the real UUID, kinda like if you logged in with that account normally.

For the second question, theoretically, you could change the uuid field, and then fake all the events and stuff, I did think of this option when making the API, however there is a lot of room for errors and it's just not that clean. "Reloading" a player like that will most likely have side effects either inside Minecraft or in other plugins. You kinda sparked my interest so I might play around with this and maybe add it if I can get it to work, no guarantees though since I am pretty busy with private stuff right now. 

Sorry  for the delay

**Comment by iMrDJAi** [comment]
@BeefDev Thank you for your reply.

This could open the opportunity for multiple profiles per player within a server, that would be fun. :)

**Comment by rievgr** [comment]
This is already possible with the current way the api works, I actually designed the api with a plugin like this in mind, but got caught up with private stuff and couldnt finish it. 

You can save the uuids of each of their profiles, then when they select one, save their real uuid and the profile one in the map and kick them, then when they join on the event set their uuid to that one

**Comment by iMrDJAi** [comment]
@BeefDev Yeah, the only limitation is that it requires the player to leave then re-join the server. Maybe we may bypass that by combining it with a BungeeCord server? Like moving the player to lobby instead of kicking him, then moving him back to the server?

**Comment by rievgr** [comment]
> @BeefDev Yeah, the only limitation is that it requires the player to leave then re-join the server. Maybe we may bypass that by combining it with a BungeeCord server? Like moving the player to lobby instead of kicking him, then moving him back to the server?

Ig so, I havent coded anything for bungeecord but if the login packets are sent like normal (I assume they are since bungeecord servers are in offline mode) then it should work fine.

**Comment by iMrDJAi** [comment]
@BeefDev I think we could take this approach at this stage, but we should look for a better one since I don't believe it is the most ideal. While this solution seems to be the easiest, unfortunately it comes at a cost.

Running an extra BungeeCord server could be limited by server hosts sometimes. It may consume more resources as well. I'm concerned about optimization and performance drop.

Also, this may require users to do an additional setup in order to get it working, it won't be as straightforward as installing a regular plugin.

About the implementation, if only we can find a way to bypass the error `You are already connected to this Server`, we may eliminate the need of a lobby. We need a way to force `/send <player-name> <server-name>` even though the player is already connected to that server.

**Comment by rievgr** [comment]
> @BeefDev I think we could take this approach at this stage, but we should look for a better one since I don't believe it is the most ideal. While this solution seems to be the easiest, unfortunately it comes at a cost.
> 
> Running an extra BungeeCord server could be limited by server hosts sometimes. It may consume more resources as well. I'm concerned about optimization and performance drop.
> 
> Also, this may require users to do an additional setup in order to get it working, it won't be as straightforward as installing a regular plugin.
> 
> About the implementation, if only we can find a way to bypass the error `You are already connected to this Server`, we may eliminate the need of a lobby. We need a way to force `/send <player-name> <server-name>` even though the player is already connected to that server.

Sorry again for the delay, I understand that having this setup will be a hassle for users (and a bit pointless in my opinion, I will look into how I can fake it, I think simply changing the UUID in the player object and then manually calling the events/sending the packets would work, although I still believe the relog method is better, I might add this and allow both options.

**Comment by iMrDJAi** [comment]
@BeefDev I think that sending fake packets wouldn't be enough, we need a plugin that acts like a middleware and handle incoming connections before getting to the server itself. I believe that it's not possible to simulate a player kick event without actually closing the connection, we need to prevent that from happening somehow. 

BTW after some researches, I found out that is possible to bypass `You are already connected to this Server` by removing that [check](https://github.com/SpigotMC/BungeeCord/blob/ff5727c5ef9c0b56ad35f9816ae6bd660b622cf0/proxy/src/main/java/net/md_5/bungee/UserConnection.java#L295) by modifying bungeecord itself, or creating a plugin to override `UserConnection#connect`. This approach has been taken by the [AutoReconnect](https://github.com/AoElite/AutoReconnect/blob/da55aa46f40fbf4ec4af0e86704bb114c4e8cb6f/src/main/java/me/aoelite/bungee/autoreconnect/ReconnectTask.java#L281) plugin.

**Comment by rievgr** [comment]
> @BeefDev I think that sending fake packets wouldn't be enough, we need a plugin that acts like a middleware and handle incoming connections before getting to the server itself. I believe that it's not possible to simulate a player kick event without actually closing the connection, we need to prevent that from happening somehow.
> 
> BTW after some researches, I found out that is possible to bypass `You are already connected to this Server` by removing that [check](https://github.com/SpigotMC/BungeeCord/blob/ff5727c5ef9c0b56ad35f9816ae6bd660b622cf0/proxy/src/main/java/net/md_5/bungee/UserConnection.java#L295) by modifying bungeecord itself, or creating a plugin to override `UserConnection#connect`. This approach has been taken by the [AutoReconnect](https://github.com/AoElite/AutoReconnect/blob/da55aa46f40fbf4ec4af0e86704bb114c4e8cb6f/src/main/java/me/aoelite/bungee/autoreconnect/ReconnectTask.java#L281) plugin.

It is possible to simulate the event, now about the packets, that'll be trickier, I think the server does close the connection on quit packet, so we could just get all their packet handlers registered by plugins and call the method using a fake packet. I will prob experiment with this a bit tomorrow, I dont think it will require such series modification.

**Comment by rievgr** [comment]
Im sorry I didnt have time to test it today (have a lot of irl stuff going on). Also mind messaging me on discord (Beefdev#5043) I don't really like using a ticket as a chat.

**Comment by iMrDJAi** [comment]
@BeefDev Hello! any new? (I sent you a friend request on Discord tho)

**Comment by rievgr** [comment]
> @BeefDev Hello! any new? (I sent you a friend request on Discord tho)

I think I accepted it (whats ur username a lot of people friended me recently) , also sorry I havent looked into this, I have a really important test in 2 days and I am preparing.

**Comment by rievgr** [comment]
Did some light testing, was able to change the fields, however as school has started I have very little time which must be spent working on some private projects which need to release soon. As this is not a bug I will not be implementing this.

If you however want it added, you can feel free to fork this project. To save you some time, you can change their UUID field in nms entity class, and the game profile field in EntityHuman. Also take a look at the nms PlayerList class for reloading players (might be useful, might not be just suggesting). I'm sorry to have kept you waiting and have a good day.
